version: '3.1'

services:
  quizgame:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command: 
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data:
